name: Auto Commit HTML Changes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make changes (example)
        run: |
          echo "<!-- Updated on $(date) -->" >> index.html

      - name: Commit and push
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update"
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main
